SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMP;

SELECT *
FROM EMP e 
WHERE UPPER(ENAME) LIKE UPPER('scott');

SELECT ENAME, LENGTH(ENAME)
FROM EMP;

SELECT ENAME, LENGTHB(ENAME)
FROM EMP;

SELECT '한글' FROM DUAL;

SELECT JOB, SUBSTR(JOB, 1, 2),SUBSTR(JOB, 3, 2),SUBSTR(JOB, -2)
FROM EMP;

SELECT 'HELLO ORACLE!' col1
, INSTR('HELLO ORACLE!','L')col2
, INSTR('HELLO ORACLE!','L',5)col3
, INSTR('HELLO ORACLE!','L',2,2)col4
FROM DUAL;

SELECT *
FROM EMP
WHERE ENAME LIKE '%S%'; 

SELECT *
FROM EMP
WHERE INSTR(ENAME,'S')>0;

SELECT '010-1234-5678' TEL
	,REPLACE('010-1234-5678','-',' ') TEL2
FROM DUAL;

SELECT 'ORACLE'
	,LPAD('ORACLE',10,'#') LPAD_1
	,RPAD('ORACLE',10,'#') RPAD_1
	,LPAD('ORACLE',10) LPAD_2
	,RPAD('ORACLE',10) RPAD_2
	,RPAD(SUBSTR('010-1234-4567',1,9),13,'*') RPAD_3
FROM DUAL;

SELECT EMPNO
	,CONCAT(EMPNO,ENAME)
	,EMPNO || ENAME
FROM EMP
WHERE ENAME = 'SCOTT';

SELECT 
	'['||' ORACLE '|| ']' col1
	,'['|| TRIM(' ORACLE ') || ']' col2
	,'['|| LTRIM(' ORACLE ') || ']' col3
	,'['|| RTRIM(' ORACLE ') || ']' col4
	,'['|| LTRIM('<ORACLE>','<') || ']' col5
FROM DUAL;

SELECT CEIL(3.14)
	  ,FLOOR(3.14)
FROM DUAL;

SELECT SYSDATE AS TODAY
	,SYSDATE -1 AS YESTERDAY
	,SYSDATE +1 AS TOMORROW
	,SYSDATE - TO_DATE('2016-07-14','YYYY-MM-DD')
	,ADD_MONTHS(SYSDATE,3)
	,ADD_MONTHS(SYSDATE,-3)
FROM DUAL;

SELECT EMPNO, ENAME
,HIREDATE - ADD_MONTHS(HIREDATE, 120)
FROM EMP;

SELECT EMPNO, ENAME
FROM EMP
WHERE ADD_MONTHS(HIREDATE, 120) < SYSDATE ;

SELECT EMPNO, ENAME
	,HIREDATE
	,TRUNC(MONTHS_BETWEEN(SYSDATE,HIREDATE))
FROM EMP;

SELECT EMPNO
	,'500' + EMPNO
	,TO_CHAR(EMPNO, '99,999') || 'ABC'
FROM EMP;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD')
FROM DUAL;

SELECT
	TO_NUMBER('1,300','999,999')+1500
	,TO_DATE('2026-07-15','YYYY-MM-DD')+2
FROM DUAL;

SELECT
	EMPNO
	,SAL + NVL(COMM,0)
	,NVL2(COMM, 'O','X')
	,NVL2(COMM, SAL*12+COMM, SAL*12)
FROM EMP;

SELECT EMPNO,ENAME,JOB,SAL
	,DECODE(JOB,
		'MANAGER', SAL * 1.1
		,'SALESMAN', SAL*1.05
		,'ANALYST',SAL
		,SAL*1.03)UPSAL
FROM EMP;

SELECT EMPNO,ENAME,JOB,SAL
	,CASE JOB
		WHEN 'MANAGER' THEN SAL * 1.1
		WHEN'SALESMAN' THEN SAL*1.05
		WHEN'ANALYST' THEN SAL
		ELSE SAL*1.03
		END UPSAL
FROM EMP;

