-- 7강 되새김 문제

-- 1번
SELECT DEPTNO, TRUNC(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL
		,MIN(SAL) MIN_SAL,COUNT(*) CNT
FROM EMP
GROUP BY DEPTNO;

-- 2번
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(*)>=3;

-- 3번
SELECT TO_CHAR(HIREDATE , 'YYYY'), DEPTNO, COUNT(*) CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE , 'YYYY'), DEPTNO;

-- 4번
SELECT NVL2(COMM,'X','O'), COUNT(*)
FROM EMP
GROUP BY NVL2(COMM,'X','O');