-- JOIN
SELECT *
FROM EMP,DEPT;

-- INNER JOIN
SELECT EMP.EMPNO, EMP.DEPTNO, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO ;

-- 별칭
SELECT E.EMPNO, E.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO ;

-- 등가조인
SELECT E.EMPNO, E.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL > 3000; -- SAL은 유일해 E.SAL로 표현 안 해도 됨
-- 자체조인
SELECT E.*, M.ENAME 상사명, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E, DEPT D, EMP M
WHERE E.DEPTNO = D.DEPTNO
AND E.MGR  = M.EMPNO ;

SELECT *
FROM SALGRADE s;

-- 비등가조인
SELECT S.GRADE, E.*, E.ENAME 상사명, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E, DEPT D, EMP M, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.MGR  = M.EMPNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL ;

SELECT *
FROM EMP;

-- 왼쪽 외부 조인(오라클)
SELECT E.*, M.ENAME 상사명, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E, DEPT D, EMP M, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.MGR  = M.EMPNO(+) -- 안나와도 되는 쪽은 +로 표기, 오라클에서만 +사용
AND E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- NATURAL JOIN
SELECT EMPNO, ENAME, DEPTNO , DNAME ,LOC 
FROM EMP E NATURAL JOIN DEPT D;

-- JOIN USING
SELECT EMPNO, ENAME, DEPTNO , DNAME ,LOC 
FROM EMP E JOIN DEPT D USING(DEPTNO);

-- JOIN ON
SELECT E.*, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO);

SELECT S.GRADE, E.*, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
		   JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL);

-- 외부 조인
SELECT S.GRADE, M.ENAME 상사명, E.*, D.DEPTNO , D.DNAME ,D.LOC 
FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
		   JOIN SALGRADE S ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
		   LEFT OUTER JOIN EMP M ON (E.MGR = M.EMPNO) ;

-- 전체 외부 조인
SELECT E.*, M.ENAME 상사명
FROM EMP E FULL OUTER JOIN EMP M
	ON E.MGR  = M.EMPNO;
