-- 8강 되새김 문제
-- 1번
-- 오라클 방식
SELECT DEPT.DEPTNO, DNAME, EMPNO, ENAME, SAL
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 2000;
-- 표준 방식
SELECT DEPT.DEPTNO, DNAME, EMPNO, ENAME, SAL
FROM EMP JOIN DEPT ON(EMP.DEPTNO = DEPT.DEPTNO)
WHERE SAL > 2000;

-- 2번
SELECT DEPTNO, DNAME, AVG(SAL), MAX(SAL), MIN(SAL), COUNT(*)
FROM EMP JOIN DEPT USING(DEPTNO)
GROUP BY DEPTNO, DNAME;

-- 3번
SELECT  D.* , E.ENAME , JOB, SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO , ENAME;

-- 4번
SELECT D.DEPTNO , D.DNAME ,E.EMPNO ,E.ENAME ,E.MGR, E.SAL
		,S.LOSAL , S.HISAL , S.GRADE , M.EMPNO ,M.ENAME 
FROM EMP E, DEPT D, SALGRADE S, EMP M
WHERE E.DEPTNO = D.DEPTNO
AND E.MGR = M.EMPNO (+)
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO , E.EMPNO ;
