-- 단일행 서브쿼리
SELECT *
FROM EMP
WHERE SAL > (
	SELECT SAL
	FROM EMP
	WHERE ENAME = 'JONES');

-- 날짜형 데이터
SELECT *
FROM EMP
WHERE HIREDATE 	< (SELECT HIREDATE 
					FROM EMP
					WHERE ENAME = 'SCOTT');

-- IN 연산자
SELECT *
FROM EMP
WHERE DEPTNO IN(20,30);

-- ANY 연산자
SELECT *
FROM EMP
WHERE SAL = ANY(SELECT MAX(SAL)
				FROM EMP
				GROUP BY DEPTNO);

-- ANY, 대소비교
SELECT *
FROM EMP
WHERE SAL < ANY(SELECT MAX(SAL)
				FROM EMP
				WHERE DEPTNO = 30);

-- ALL
SELECT *
FROM EMP
WHERE SAL < ALL (SELECT SAL
				FROM EMP
				WHERE DEPTNO = 30);

-- EXISTS
SELECT *
FROM EMP
WHERE EXISTS(SELECT DNAME
			FROM DEPT
			WHERE DEPTNO = 10);

-- 다중열 서브쿼리
SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
						FROM EMP GROUP BY DEPTNO);

-- 인라인 뷰
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC 
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E,
	(SELECT * FROM DEPT) D
WHERE E.DEPTNO = D.DEPTNO ;

-- WITH절
WITH
E AS (SELECT * FROM EMP WHERE DEPTNO = 10),
D AS (SELECT * FROM DEPT)
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC 
FROM E,D
WHERE E.DEPTNO = D.DEPTNO;

-- 스칼라 서브쿼리
SELECT EMPNO, ENAME, JOB, SAL,
		(SELECT GRADE FROM SALGRADE
		WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
		DEPTNO, (SELECT DNAME FROM DEPT
				WHERE E.DEPTNO = DEPT.DEPTNO)
FROM EMP E;






