-- 9강 되새김 문제
-- 1번
-- ALLEN과 같은 직책인 사원 정보 출력
SELECT JOB, EMPNO, ENAME, SAL, D.DEPTNO AS DEPTNO, DNAME
FROM EMP E JOIN DEPT D ON(E.DEPTNO = D.DEPTNO) 
WHERE JOB = (SELECT JOB FROM EMP
			WHERE ENAME = 'ALLEN')
ORDER BY SAL DESC;

-- 2번
-- 평균 급여보다 많이 받는 사원의 정보(사원,부서,급여 정보)
-- 정렬 급여 많은 순, 사원번호 오름차순
SELECT EMPNO, ENAME, DNAME, HIREDATE, LOC, SAL, GRADE
FROM EMP, DEPT, SALGRADE
WHERE EMP.DEPTNO = DEPT.DEPTNO
	AND EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL
	AND EMP.SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO;

-- 3번
-- 10번 부서 사원 중 30번 부서에 없는 직책인 사원,부서 정보 출력
SELECT EMPNO, ENAME, JOB, D.DEPTNO, DNAME, LOC
FROM EMP E JOIN DEPT D ON (E.DEPTNO =D.DEPTNO)
WHERE D.DEPTNO = 10 
AND JOB NOT IN(SELECT JOB FROM EMP 
					WHERE DEPTNO = 30);

-- 4번
-- SALESMAN 최고 급여보다 많이 받는 사원의 사원,등급 정보 출력
-- 다중행 O
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND SAL > ALL(SELECT SAL FROM EMP
			WHERE JOB = 'SALESMAN')
ORDER BY EMPNO;
-- 다중행X
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND SAL > (SELECT MAX(SAL) FROM EMP
			WHERE JOB = 'SALESMAN')
ORDER BY EMPNO;


