-- CREATE TABLE
CREATE TABLE DEPT_TEMP
	AS SELECT * FROM DEPT;

SELECT *
FROM DEPT_TEMP dt;

CREATE TABLE EMP_TEMP
	AS SELECT * FROM EMP
WHERE 1 != 1; -- 안에 데이터는 만들어 지지 않음

SELECT *
FROM EMP_TEMP;

-- DROP TABLE
DROP TABLE EMP_TEMP;

-- INSERT
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
	VALUES ( 50, 'DATABASE','SEOUL'); -- 짝을 맞춰야 함
	
INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
	VALUES ( 60, 'NETWORK','BUSAN');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME)
	VALUES ( 70, 'WEB'); -- 짝을 맞추면 모든 열 없어도 됨
	
INSERT INTO DEPT_TEMP
	VALUES ( 80, 'SERVER','FRANCE');

-- DATE입력
INSERT INTO EMP_TEMP
		VALUES (9999,'홍길동','PRESIDENT',NULL,'2001/01/01',
				5000,1000,10);

INSERT INTO EMP_TEMP
		VALUES(2121,'이순신','MANAGER',9999,
			TO_DATE('07/01/2001','DD/MM/YYYY'), -- TO_DATE 사용
			5000,1000,10);

-- INSERT 서브쿼리
INSERT INTO EMP_TEMP
	(SELECT E.*
	FROM EMP E, SALGRADE S
	WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
	AND S.GRADE = 1);

-- UPDATE
CREATE TABLE DEPT_TEMP2 AS
SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP2;

-- 모든 데이터 UPDATE
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL';

-- 일부 UPDATE
UPDATE DEPT_TEMP2
SET LOC = 'DALLAS'
WHERE DEPTNO = 30;

ROLLBACK;

-- 서브쿼리 UPDATE
UPDATE DEPT_TEMP2
SET (DNAME,LOC) = (SELECT DNAME, LOC
					FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;



-- DELETE
DELETE FROM EMP_TEMP; -- 조건 없으면 다 지움

DELETE FROM EMP_TEMP
WHERE EMPNO = 7369;











