-- CREATE TABLE
CREATE TABLE EMP_DDL
 ("EMPNO" NUMBER(4,0), 
	"ENAME" VARCHAR2(10), 
	"JOB" VARCHAR2(9), 
	"MGR" NUMBER(4,0), 
	"HIREDATE" DATE, 
	"SAL" NUMBER(7,2), 
	"COMM" NUMBER(7,2), 
	"DEPTNO" NUMBER(2,0));

SELECT * FROM EMP_DDL;

-- CREATE 복사
CREATE TABLE DEPT_DDL AS
	SELECT * FROM DEPT;

-- CREATE 조건절
CREATE TABLE DEPT_DDL_30 AS
	SELECT * FROM DEPT
	WHERE DEPTNO = 30;

SELECT * FROM DEPT_DDL_30;

-- ALTER TABLE
CREATE TABLE EMP_ALTER AS
	SELECT * FROM EMP;

-- ADD
ALTER TABLE EMP_ALTER ADD HP VARCHAR2(100) NULL;

SELECT * FROM EMP_ALTER;

--RENAME
ALTER TABLE EMP_ALTER RENAME COLUMN HP TO TEL;

--MODIFY
ALTER TABLE EMP_ALTER MODIFY EMPNO NUMBER(5);

SELECT * FROM EMP_ALTER;

-- DROP
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

-- RENAME TABLE
RENAME EMP_ALTER TO EMP_RENAME;

-- TRUNCATE
TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

-- DROP
DROP TABLE EMP_RENAME ;


