-- 12강 되새김 문제
-- 1번
CREATE TABLE EMP_HW(
	EMPNO NUMBER(4),
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2)
);

-- 2번
-- BIGO 열 추가
ALTER TABLE EMP_HW 
ADD BIGO VARCHAR2(20);

-- 3번
-- BIGO 열 크기 변경
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);

-- 4번
-- REMARK로 이름 변경
ALTER TABLE EMP_HW 
RENAME COLUMN BIGO TO REMARK;

-- 5번
-- EMP 데이터를 모두 저장
INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT * FROM EMP;

SELECT * FROM EMP_HW;

-- 6번
-- 테이블 삭제
DROP TABLE EMP_HW;
