-- DICT 조회
SELECT * FROM DICT;

-- USER_
SELECT TABLE_NAME
FROM USER_TABLES;

-- ALL
SELECT OWNER, TABLE_NAME
FROM ALL_TABLES;

-- DBA
SELECT * FROM DBA_TABLES;

-- 인덱스 정보 열람
SELECT * FROM USER_INDEXES;

-- INDEX 생성
CREATE INDEX IDX_EMP_SAL
	ON EMP(SAL);

SELECT * FROM USER_IND_COLUMNS;

-- INDEX 삭제
DROP INDEX IDX_EMP_SAL;

--뷰 권한,CMD에서 SYSTEM으로 접속 후 실행
GRANT CREATE VIEW TO SCOTT;

-- 뷰 생성
CREATE VIEW VW_EMP20
	AS (SELECT EMPNO, ENAME, JOB, DEPTNO
		FROM EMP
		WHERE DEPTNO=20);
-- 뷰 확인
SELECT * FROM VW_EMP20;

-- 뷰 삭제
DROP VIEW VW_EMP20;

-- SEQUENCE
CREATE TABLE DEPT_SEQUENCE
	AS SELECT * FROM DEPT
	WHERE 1 <> 1;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 10
START WITH 10
MAXVALUE 90
MINVALUE 10
NOCYCLE
CACHE 2;

INSERT INTO DEPT_SEQUENCE(DEPTNO, DNAME, LOC)
VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE','SEOUL');

SELECT * FROM DEPT_SEQUENCE;

-- SEQUENCE 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;

-- DROP SEQUENCE
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

-- SYNONYM
CREATE SYNONYM E FOR EMP;

SELECT * FROM E;

-- SYNONYM 삭제
DROP SYNONYM E;

