-- NOT NULL
CREATE TABLE TABLE_NOTNULL(
	LOGIN_ID VARCHAR2(20) NOT NULL,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
)

INSERT INTO TABLE_NOTNULL VALUES('TEST_ID_01','PWD','010-1234-5678');

SELECT * FROM TABLE_NOTNULL;
-- 오류
INSERT INTO TABLE_NOTNULL VALUES('TEST_ID_01',NULL,'010-1234-5678');

INSERT INTO TABLE_NOTNULL(LOGIN_ID, LOGIN_PWD) 
VALUES('TEST_ID_01','PWD'); -- TEL은 NULL 가능

--제약조건 확인
SELECT OWNER, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
	FROM USER_CONSTRAINTS;

--이름 지정
CREATE TABLE TABLE_NOTNULL2(
	LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL,
	LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL,
	TEL VARCHAR2(20)
)
-- 조건 추가
ALTER TABLE TABLE_NOTNULL
MODIFY(TEL NOT NULL);

UPDATE TABLE_NOTNULL
	SET TEL = '010-1234-5679'
	WHERE TEL IS NULL;

-- 이름 지정 추가
ALTER TABLE TABLE_NOTNULL2
MODIFY(TEL CONSTRAINT TELNN_TEL_NN NOT NULL);

SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_NOTNULL';

--제약 조건 이름 변경
ALTER TABLE TABLE_NOTNULL2
RENAME CONSTRAINT TELNN_TEL_NN TO TELNN2_TEL_NN;

-- 제약 조건 삭제
ALTER TABLE TABLE_NOTNULL2
DROP CONSTRAINT TELNN2_TEL_NN;

--UNIQUE
CREATE TABLE TABLE_UNIQUE(
LOGIN_ID VARCHAR2(20) UNIQUE,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
)

INSERT INTO TABLE_UNIQUE
	VALUES('TEST_ID_01','PWD01','010-1234-5678');
INSERT INTO TABLE_UNIQUE
	VALUES('TEST_ID_01','PWD01','010-1111-2222');
--NULL값 추가
INSERT INTO TABLE_UNIQUE
	VALUES('NULL','PWD01','010-1111-2222');
	

SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE,
       TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'TABLE_UNIQUE';

-- PRIMARY KEY
CREATE TABLE TABLE_PK(
	LOGIN_ID VARCHAR2(20) PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) NOT NULL,
	TEL VARCHAR2(20)
);

--FOREIGN KEY
CREATE TABLE DEPT_FK(
	DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
	DNAME VARCHAR2(14),
	LOC VARCHAR2(13)
);
CREATE TABLE EMP_FK(
	EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
	ENAME VARCHAR2(10),
	JOB VARCHAR2(9),
	MGR NUMBER(4),
	HIREDATE DATE,
	SAL NUMBER(7,2),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO)
);
-- 부모테이블에 없는 값 생성
INSERT INTO EMP_FK 
VALUES(9999, 'TEST_NAME', 'TEST_JOB', NULL, TO_DATE('2001/01/01','YYYY/MM/DD'),
		300,NULL,10);

INSERT INTO DEPT_FK
VALUES(10,'TEST_DNAME','TEST_LOC');

-- 참조 데이터 삭제
DELETE FROM DEPT_FK
WHERE DEPTNO = 10;

-- CHECK
CREATE TABLE TABLE_CHECK(
	LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) >3),
	TEL VARCHAR2(20)
);

-- DEFAULT
CREATE TABLE TABLE_DEFAULT(
	LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY,
	LOGIN_PWD VARCHAR2(20) DEFAULT '1234',
	TEL VARCHAR2(20)
);

