-- 14강 되새김 문제
CREATE TABLE DEPT_CONST(
	DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
	DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
	LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
);

CREATE TABLE EMP_CONST(
	EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
	ENMAE VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
	JOB VARCHAR2(9),
	TEL VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
	HIREDATE DATE,
	SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK(SAL BETWEEN 1000 AND 9999),
	COMM NUMBER(7,2),
	DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

SELECT TABLE_NAME,
	   CONSTRAINT_NAME,
       CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPT_CONST'
	OR TABLE_NAME = 'EMP_CONST'
ORDER BY CONSTRAINT_NAME;
